[package]
name = "qxync-cli"
description = "qsync 命令行（M0：login/ls/stat/get/put/mkdir/status）"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "qsync"
path = "src/main.rs"

[dependencies]
qxync-core = { path = "../qxync-core" }
qxync-client = { path = "../qxync-client" }
qxync-fuse = { path = "../qxync-fuse" }
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
libc = "0.2"
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
